FROM node:16-alpine

RUN npm install -g @angular/cli@14.2

RUN mkdir /build
WORKDIR /build

COPY frontend .
COPY backend/src/globals.ts src/app/globals.ts
COPY backend/src/dto src/app/classes/dto
RUN npm i
RUN ng build

ENTRYPOINT sh
